export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_DIFFICULTY = 'UPDATE_DIFFICULTY';
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS';
export const UPDATE_CURRENT_DIFFICULTY = 'UPDATE_CURRENT_DIFFICULTY';
